# FAQ- en privacyteksten in 23 talen. Sleutels: faq.q1..q8, faq.a1..a8, priv.h1..h5, priv.p1..p5,
# pages.faq (menu), pages.privacy (menu), pages.open ("Open Whenly").
# GITHUB = plaats van de link (wordt in de pagina een <a>).
P = {}

P['en'] = dict(
 faq_title='Frequently asked questions', priv_title='Privacy', open='Open Whenly', faq='FAQ', privacy='Privacy',
 q=['Is Whenly free?','Do I need an account?','Does it work on my phone?','Which languages does Whenly support?','How is it different from Doodle?','Can I fill in dates for someone else?','Who can see my poll?','What happens to my data?'],
 a=['Yes. Whenly is completely free and stays free. No paywall, no ads.',
    'No. Nobody needs an account, not even the person who creates the poll. Type your name and tap your days.',
    'Yes. Whenly works in any browser and can be added to your home screen like an app, no app store needed.',
    'Twenty-three, including English, French, Spanish, Arabic, Hindi, Chinese, Russian, Tamazight, Kurdish and Shona. It follows your browser language and you can switch with the globe button.',
    'Whenly asks nobody to sign up, shows no ads and is free. You tap days on a calendar, and a traffic light shows when everyone can make it.',
    'Yes. Choose "Add a participant", type a name and tap the days for that person.',
    'Anyone with the link. The link is a long random code that cannot be guessed, and poll pages are not indexed by search engines. Share the link only with your group.',
    'Only the title, the names and the tapped days are stored, nothing else. No email address, no phone number, no tracking. You are in control: anyone with the link can delete the poll completely, and then everything is gone for good. If nobody deletes it, it stays 12 months after the last activity so you can come back to it, then it is deleted automatically.'],
 h=['What Whenly stores','What Whenly does not do','Who can see a poll','How long, and who decides','Where, and questions'],
 p=['Only what you type yourself: the poll title, the participants\' names, the tapped days and an optional time. Nothing else. No email address, no phone number, no account, no password.',
    'No tracking, no ads, no third-party cookies, no analytics. Your browser locally remembers only your language, your name and which polls you opened, so you do not have to retype anything. That stays on your own device.',
    'Anyone with the link. The link is a long random code that cannot be guessed, and poll pages are not indexed by search engines, so share the link only with your group. Anyone with the link can also change or remove names and days; when someone removes a name, a short note stays visible for 30 days so the group knows it was not an app error.',
    'You do. Next to the title there is "Delete this poll completely". Click it (and confirm) and the title, all names and all tapped days are gone immediately and for good, for everyone. If nobody deletes it, the poll stays for 12 months after the last activity so you can come back to it. That is not to collect data; after that it is deleted automatically. A removed name disappears for good after 30 days.',
    'Data is stored on Cloudflare servers. Whenly is open source; the code and any questions go to GITHUB.'])

P['nl'] = dict(
 faq_title='Veelgestelde vragen', priv_title='Privacy', open='Open Whenly', faq='FAQ', privacy='Privacy',
 q=['Is Whenly gratis?','Moet ik een account maken?','Werkt het op mijn telefoon?','In welke talen werkt Whenly?','Wat is het verschil met Doodle?','Kan ik voor iemand anders een datum invullen?','Wie kan mijn afspraak zien?','Wat gebeurt er met mijn gegevens?'],
 a=['Ja. Whenly is volledig gratis en blijft gratis. Geen betaalmuur, geen reclame.',
    'Nee. Niemand hoeft een account te maken, ook niet wie de afspraak aanmaakt. Je typt je naam en klikt je dagen aan.',
    'Ja. Whenly werkt in elke browser en kan als app op je startscherm worden gezet, zonder appstore.',
    'Drieëntwintig, waaronder Nederlands, Frans, Engels, Arabisch, Hindi, Chinees, Russisch, Tamazight, Koerdisch en Shona. De taal volgt je browser en is te wisselen via de wereldbol.',
    'Whenly vraagt niemand om te registreren, toont geen reclame en is gratis. Je klikt dagen aan op een kalender, en een stoplicht toont wanneer iedereen kan.',
    'Ja. Kies "Lid toevoegen", typ een naam en klik de dagen voor die persoon aan.',
    'Iedereen met de link. De link is een lange willekeurige code die niet te raden is, en afspraakpagina\'s worden niet door zoekmachines geïndexeerd. Deel de link dus alleen met je groep.',
    'Alleen de titel, de namen en de aangeklikte dagen worden bewaard, niets anders. Geen e-mailadres, geen telefoonnummer, geen tracking. Jij hebt er controle over: iedereen met de link kan de afspraak volledig verwijderen, en dan is alles definitief weg. Verwijdert niemand ze, dan blijft ze 12 maanden na de laatste activiteit staan zodat je er later op kunt terugkomen, daarna wordt ze automatisch gewist.'],
 h=['Wat Whenly bewaart','Wat Whenly niet doet','Wie een afspraak kan zien','Hoe lang, en wie beslist','Waar, en vragen'],
 p=['Alleen wat je zelf intypt: de titel van de afspraak, de namen van de deelnemers, de aangeklikte dagen en eventueel een uur. Verder niets. Geen e-mailadres, geen telefoonnummer, geen account, geen wachtwoord.',
    'Geen tracking, geen reclame, geen cookies van derden, geen analytics. Je browser onthoudt lokaal alleen je taal, je naam en welke afspraken je opende, zodat je niets opnieuw hoeft te typen. Dat blijft op je eigen toestel.',
    'Iedereen met de link. De link is een lange willekeurige code die niet te raden is, en afspraakpagina\'s worden niet door zoekmachines geïndexeerd; deel de link dus alleen met je groep. Iedereen met de link kan ook namen en dagen aanpassen of weghalen; als iemand een naam weghaalt, blijft dat 30 dagen als korte melding zichtbaar zodat de groep weet dat het geen fout van de app was.',
    'Jij. Bij de titel staat "Afspraak volledig verwijderen". Klik je daarop (en bevestig je), dan zijn de titel, alle namen en alle aangeklikte dagen meteen en definitief weg, voor iedereen. Verwijdert niemand ze, dan blijft de afspraak 12 maanden na de laatste activiteit staan zodat je er later op kunt terugkomen. Dat is niet om gegevens te verzamelen; daarna wordt ze automatisch gewist. Een weggehaalde naam verdwijnt definitief na 30 dagen.',
    'De gegevens staan op servers van Cloudflare. Whenly is open source; de code en je vragen vind je op GITHUB.'])

P['fr'] = dict(
 faq_title='Questions fréquentes', priv_title='Confidentialité', open='Ouvrir Whenly', faq='FAQ', privacy='Confidentialité',
 q=['Whenly est-il gratuit ?','Faut-il un compte ?','Ça marche sur mon téléphone ?','Quelles langues Whenly propose-t-il ?','Quelle différence avec Doodle ?','Puis-je remplir pour quelqu\'un d\'autre ?','Qui peut voir mon rendez-vous ?','Que deviennent mes données ?'],
 a=['Oui. Whenly est entièrement gratuit et le reste. Pas de mur payant, pas de pub.',
    'Non. Personne n\'a besoin de compte, même pas la personne qui crée le rendez-vous. Tu tapes ton prénom et tu coches tes jours.',
    'Oui. Whenly fonctionne dans n\'importe quel navigateur et s\'ajoute à l\'écran d\'accueil comme une appli, sans app store.',
    'Vingt-trois, dont le français, l\'anglais, l\'espagnol, l\'arabe, le hindi, le chinois, le russe, le tamazight, le kurde et le shona. La langue suit ton navigateur et se change avec le globe.',
    'Whenly ne demande à personne de s\'inscrire, n\'affiche pas de pub et est gratuit. Tu coches des jours sur un calendrier, et un feu tricolore montre quand tout le monde peut.',
    'Oui. Choisis « Ajouter un participant », tape un prénom et coche les jours pour cette personne.',
    'Toute personne qui a le lien. Le lien est un long code aléatoire impossible à deviner, et les pages de rendez-vous ne sont pas indexées par les moteurs de recherche. Ne partage le lien qu\'avec ton groupe.',
    'Seuls le titre, les prénoms et les jours cochés sont conservés, rien d\'autre. Pas d\'e-mail, pas de téléphone, pas de suivi. Tu gardes le contrôle : toute personne avec le lien peut supprimer le rendez-vous complètement, et tout disparaît pour de bon. Si personne ne le supprime, il reste 12 mois après la dernière activité pour que tu puisses y revenir, puis il est supprimé automatiquement.'],
 h=['Ce que Whenly conserve','Ce que Whenly ne fait pas','Qui peut voir un rendez-vous','Combien de temps, et qui décide','Où, et questions'],
 p=['Uniquement ce que tu tapes : le titre du rendez-vous, les prénoms des participants, les jours cochés et éventuellement une heure. Rien d\'autre. Pas d\'e-mail, pas de téléphone, pas de compte, pas de mot de passe.',
    'Pas de suivi, pas de pub, pas de cookies tiers, pas d\'analytics. Ton navigateur retient seulement, localement, ta langue, ton prénom et les rendez-vous ouverts, pour ne rien retaper. Ça reste sur ton appareil.',
    'Toute personne qui a le lien. Le lien est un long code aléatoire impossible à deviner, et les pages de rendez-vous ne sont pas indexées par les moteurs de recherche ; ne partage le lien qu\'avec ton groupe. Toute personne avec le lien peut aussi modifier ou retirer des prénoms et des jours ; quand quelqu\'un retire un prénom, une courte note reste visible 30 jours pour que le groupe sache que ce n\'était pas une erreur de l\'appli.',
    'Toi. À côté du titre se trouve « Supprimer ce rendez-vous complètement ». Clique (et confirme) : le titre, tous les prénoms et tous les jours cochés disparaissent immédiatement et pour de bon, pour tout le monde. Si personne ne le supprime, le rendez-vous reste 12 mois après la dernière activité pour que tu puisses y revenir. Ce n\'est pas pour collecter des données ; ensuite il est supprimé automatiquement. Un prénom retiré disparaît définitivement après 30 jours.',
    'Les données sont hébergées sur les serveurs de Cloudflare. Whenly est open source ; le code et tes questions sont sur GITHUB.'])

P['de'] = dict(
 faq_title='Häufige Fragen', priv_title='Datenschutz', open='Whenly öffnen', faq='FAQ', privacy='Datenschutz',
 q=['Ist Whenly kostenlos?','Brauche ich ein Konto?','Funktioniert es auf meinem Handy?','Welche Sprachen unterstützt Whenly?','Was ist der Unterschied zu Doodle?','Kann ich für jemand anderen eintragen?','Wer kann meine Umfrage sehen?','Was passiert mit meinen Daten?'],
 a=['Ja. Whenly ist komplett kostenlos und bleibt es. Keine Bezahlschranke, keine Werbung.',
    'Nein. Niemand braucht ein Konto, auch nicht, wer die Umfrage erstellt. Du tippst deinen Namen ein und klickst deine Tage an.',
    'Ja. Whenly läuft in jedem Browser und lässt sich wie eine App zum Startbildschirm hinzufügen, ohne App Store.',
    'Dreiundzwanzig, darunter Deutsch, Englisch, Französisch, Arabisch, Hindi, Chinesisch, Russisch, Tamazight, Kurdisch und Shona. Die Sprache folgt deinem Browser und lässt sich über die Weltkugel wechseln.',
    'Whenly verlangt keine Registrierung, zeigt keine Werbung und ist kostenlos. Du klickst Tage in einem Kalender an, und eine Ampel zeigt, wann alle können.',
    'Ja. Wähle „Teilnehmer hinzufügen“, tippe einen Namen ein und klicke die Tage für diese Person an.',
    'Jeder mit dem Link. Der Link ist ein langer Zufallscode, der sich nicht erraten lässt, und Umfrageseiten werden von Suchmaschinen nicht indexiert. Teile den Link nur mit deiner Gruppe.',
    'Nur Titel, Namen und angeklickte Tage werden gespeichert, sonst nichts. Keine E-Mail, keine Telefonnummer, kein Tracking. Du hast die Kontrolle: Jeder mit dem Link kann die Umfrage vollständig löschen, dann ist alles endgültig weg. Löscht sie niemand, bleibt sie 12 Monate nach der letzten Aktivität bestehen, damit du darauf zurückkommen kannst; danach wird sie automatisch gelöscht.'],
 h=['Was Whenly speichert','Was Whenly nicht tut','Wer eine Umfrage sehen kann','Wie lange, und wer entscheidet','Wo, und Fragen'],
 p=['Nur, was du selbst eintippst: den Titel der Umfrage, die Namen der Teilnehmer, die angeklickten Tage und optional eine Uhrzeit. Sonst nichts. Keine E-Mail, keine Telefonnummer, kein Konto, kein Passwort.',
    'Kein Tracking, keine Werbung, keine Drittanbieter-Cookies, keine Analytics. Dein Browser merkt sich lokal nur deine Sprache, deinen Namen und welche Umfragen du geöffnet hast, damit du nichts neu tippen musst. Das bleibt auf deinem Gerät.',
    'Jeder mit dem Link. Der Link ist ein langer Zufallscode, der sich nicht erraten lässt, und Umfrageseiten werden von Suchmaschinen nicht indexiert; teile den Link also nur mit deiner Gruppe. Jeder mit dem Link kann auch Namen und Tage ändern oder entfernen; entfernt jemand einen Namen, bleibt 30 Tage ein kurzer Hinweis sichtbar, damit die Gruppe weiß, dass es kein Fehler der App war.',
    'Du. Neben dem Titel steht „Diese Umfrage vollständig löschen“. Klick darauf (und bestätige), dann sind Titel, alle Namen und alle angeklickten Tage sofort und endgültig weg, für alle. Löscht sie niemand, bleibt die Umfrage 12 Monate nach der letzten Aktivität bestehen, damit du darauf zurückkommen kannst. Das dient nicht dem Sammeln von Daten; danach wird sie automatisch gelöscht. Ein entfernter Name verschwindet nach 30 Tagen endgültig.',
    'Die Daten liegen auf Servern von Cloudflare. Whenly ist Open Source; Code und Fragen findest du auf GITHUB.'])

P['es'] = dict(
 faq_title='Preguntas frecuentes', priv_title='Privacidad', open='Abrir Whenly', faq='FAQ', privacy='Privacidad',
 q=['¿Whenly es gratis?','¿Necesito una cuenta?','¿Funciona en mi teléfono?','¿Qué idiomas admite Whenly?','¿En qué se diferencia de Doodle?','¿Puedo rellenar por otra persona?','¿Quién puede ver mi encuesta?','¿Qué pasa con mis datos?'],
 a=['Sí. Whenly es totalmente gratis y seguirá siéndolo. Sin muro de pago, sin anuncios.',
    'No. Nadie necesita cuenta, ni siquiera quien crea la encuesta. Escribes tu nombre y marcas tus días.',
    'Sí. Whenly funciona en cualquier navegador y se añade a la pantalla de inicio como una app, sin tienda de apps.',
    'Veintitrés, entre ellos español, inglés, francés, árabe, hindi, chino, ruso, tamazight, kurdo y shona. Sigue el idioma de tu navegador y se cambia con el globo.',
    'Whenly no pide registro, no muestra anuncios y es gratis. Marcas días en un calendario, y un semáforo muestra cuándo pueden todos.',
    'Sí. Elige "Añadir participante", escribe un nombre y marca los días para esa persona.',
    'Cualquiera con el enlace. El enlace es un código largo y aleatorio imposible de adivinar, y las páginas de encuestas no las indexan los buscadores. Comparte el enlace solo con tu grupo.',
    'Solo se guardan el título, los nombres y los días marcados, nada más. Sin correo, sin teléfono, sin rastreo. Tú tienes el control: cualquiera con el enlace puede eliminar la encuesta por completo, y todo desaparece para siempre. Si nadie la elimina, se conserva 12 meses tras la última actividad para que puedas volver, y luego se borra automáticamente.'],
 h=['Qué guarda Whenly','Qué no hace Whenly','Quién puede ver una encuesta','Cuánto tiempo, y quién decide','Dónde, y preguntas'],
 p=['Solo lo que tú escribes: el título de la encuesta, los nombres de los participantes, los días marcados y, si quieres, una hora. Nada más. Sin correo, sin teléfono, sin cuenta, sin contraseña.',
    'Sin rastreo, sin anuncios, sin cookies de terceros, sin analítica. Tu navegador recuerda localmente solo tu idioma, tu nombre y qué encuestas abriste, para que no tengas que volver a escribir nada. Eso se queda en tu dispositivo.',
    'Cualquiera con el enlace. El enlace es un código largo y aleatorio imposible de adivinar, y las páginas de encuestas no las indexan los buscadores; comparte el enlace solo con tu grupo. Cualquiera con el enlace también puede cambiar o quitar nombres y días; si alguien quita un nombre, queda una nota breve visible 30 días para que el grupo sepa que no fue un error de la app.',
    'Tú. Junto al título está "Eliminar esta encuesta por completo". Púlsalo (y confirma) y el título, todos los nombres y todos los días marcados desaparecen de inmediato y para siempre, para todos. Si nadie la elimina, la encuesta se conserva 12 meses tras la última actividad para que puedas volver. No es para recopilar datos; después se borra automáticamente. Un nombre quitado desaparece definitivamente a los 30 días.',
    'Los datos se guardan en servidores de Cloudflare. Whenly es de código abierto; el código y tus preguntas están en GITHUB.'])

P['pt'] = dict(
 faq_title='Perguntas frequentes', priv_title='Privacidade', open='Abrir o Whenly', faq='FAQ', privacy='Privacidade',
 q=['O Whenly é grátis?','Preciso de conta?','Funciona no meu telemóvel?','Que línguas tem o Whenly?','Qual é a diferença para o Doodle?','Posso preencher por outra pessoa?','Quem pode ver a minha votação?','O que acontece aos meus dados?'],
 a=['Sim. O Whenly é totalmente grátis e assim continua. Sem paywall, sem anúncios.',
    'Não. Ninguém precisa de conta, nem quem cria a votação. Escreves o teu nome e marcas os teus dias.',
    'Sim. O Whenly funciona em qualquer browser e pode ser adicionado ao ecrã inicial como uma app, sem loja de apps.',
    'Vinte e três, incluindo português, inglês, francês, árabe, hindi, chinês, russo, tamazight, curdo e shona. Segue a língua do browser e muda-se com o globo.',
    'O Whenly não pede registo, não mostra anúncios e é grátis. Marcas dias num calendário, e um semáforo mostra quando todos podem.',
    'Sim. Escolhe "Adicionar participante", escreve um nome e marca os dias dessa pessoa.',
    'Qualquer pessoa com o link. O link é um código longo e aleatório impossível de adivinhar, e as páginas de votação não são indexadas pelos motores de busca. Partilha o link só com o teu grupo.',
    'Só o título, os nomes e os dias marcados são guardados, nada mais. Sem e-mail, sem telefone, sem rastreio. Tu tens o controlo: qualquer pessoa com o link pode apagar a votação por completo, e tudo desaparece de vez. Se ninguém a apagar, fica 12 meses após a última atividade para poderes voltar, e depois é apagada automaticamente.'],
 h=['O que o Whenly guarda','O que o Whenly não faz','Quem pode ver uma votação','Durante quanto tempo, e quem decide','Onde, e perguntas'],
 p=['Só o que tu escreves: o título da votação, os nomes dos participantes, os dias marcados e, se quiseres, uma hora. Nada mais. Sem e-mail, sem telefone, sem conta, sem palavra-passe.',
    'Sem rastreio, sem anúncios, sem cookies de terceiros, sem analytics. O teu browser guarda localmente só a tua língua, o teu nome e as votações que abriste, para não teres de escrever nada de novo. Isso fica no teu aparelho.',
    'Qualquer pessoa com o link. O link é um código longo e aleatório impossível de adivinhar, e as páginas de votação não são indexadas pelos motores de busca; partilha o link só com o teu grupo. Qualquer pessoa com o link também pode alterar ou remover nomes e dias; quando alguém remove um nome, fica uma nota breve visível 30 dias para o grupo saber que não foi erro da app.',
    'Tu. Ao lado do título está "Apagar esta votação por completo". Clica (e confirma) e o título, todos os nomes e todos os dias marcados desaparecem de imediato e de vez, para toda a gente. Se ninguém a apagar, a votação fica 12 meses após a última atividade para poderes voltar. Não é para recolher dados; depois é apagada automaticamente. Um nome removido desaparece de vez ao fim de 30 dias.',
    'Os dados ficam em servidores da Cloudflare. O Whenly é open source; o código e as perguntas estão no GITHUB.'])

P['pl'] = dict(
 faq_title='Częste pytania', priv_title='Prywatność', open='Otwórz Whenly', faq='FAQ', privacy='Prywatność',
 q=['Czy Whenly jest darmowe?','Czy potrzebuję konta?','Czy działa na telefonie?','Jakie języki obsługuje Whenly?','Czym różni się od Doodle?','Czy mogę wypełnić za kogoś innego?','Kto może zobaczyć moją ankietę?','Co dzieje się z moimi danymi?'],
 a=['Tak. Whenly jest całkowicie darmowe i takie pozostanie. Bez paywalla, bez reklam.',
    'Nie. Nikt nie potrzebuje konta, nawet osoba tworząca ankietę. Wpisujesz imię i zaznaczasz dni.',
    'Tak. Whenly działa w każdej przeglądarce i można je dodać do ekranu głównego jak aplikację, bez sklepu.',
    'Dwadzieścia trzy, w tym polski, angielski, francuski, arabski, hindi, chiński, rosyjski, tamazight, kurdyjski i shona. Język podąża za przeglądarką i można go zmienić globusem.',
    'Whenly nie wymaga rejestracji, nie pokazuje reklam i jest darmowe. Zaznaczasz dni w kalendarzu, a sygnalizacja pokazuje, kiedy wszyscy mogą.',
    'Tak. Wybierz „Dodaj uczestnika”, wpisz imię i zaznacz dni za tę osobę.',
    'Każdy, kto ma link. Link to długi losowy kod, którego nie da się zgadnąć, a strony ankiet nie są indeksowane przez wyszukiwarki. Udostępniaj link tylko swojej grupie.',
    'Zapisywane są tylko tytuł, imiona i zaznaczone dni, nic więcej. Bez e-maila, bez telefonu, bez śledzenia. Masz kontrolę: każdy z linkiem może całkowicie usunąć ankietę i wtedy wszystko znika na dobre. Jeśli nikt jej nie usunie, zostaje 12 miesięcy od ostatniej aktywności, żebyś mógł do niej wrócić, a potem jest usuwana automatycznie.'],
 h=['Co Whenly przechowuje','Czego Whenly nie robi','Kto może zobaczyć ankietę','Jak długo i kto decyduje','Gdzie, i pytania'],
 p=['Tylko to, co sam wpiszesz: tytuł ankiety, imiona uczestników, zaznaczone dni i ewentualnie godzinę. Nic więcej. Bez e-maila, bez telefonu, bez konta, bez hasła.',
    'Bez śledzenia, bez reklam, bez ciasteczek stron trzecich, bez analityki. Twoja przeglądarka zapamiętuje lokalnie tylko język, imię i otwarte ankiety, żebyś nie musiał nic wpisywać ponownie. To zostaje na twoim urządzeniu.',
    'Każdy, kto ma link. Link to długi losowy kod, którego nie da się zgadnąć, a strony ankiet nie są indeksowane przez wyszukiwarki; udostępniaj link tylko swojej grupie. Każdy z linkiem może też zmieniać lub usuwać imiona i dni; gdy ktoś usunie imię, przez 30 dni widać krótką notatkę, żeby grupa wiedziała, że to nie błąd aplikacji.',
    'Ty. Obok tytułu jest „Usuń tę ankietę całkowicie”. Kliknij (i potwierdź), a tytuł, wszystkie imiona i wszystkie zaznaczone dni znikną natychmiast i na dobre, dla wszystkich. Jeśli nikt jej nie usunie, ankieta zostaje 12 miesięcy od ostatniej aktywności, żebyś mógł do niej wrócić. Nie chodzi o zbieranie danych; potem jest usuwana automatycznie. Usunięte imię znika na dobre po 30 dniach.',
    'Dane są przechowywane na serwerach Cloudflare. Whenly jest open source; kod i pytania znajdziesz na GITHUB.'])

P['uk'] = dict(
 faq_title='Часті запитання', priv_title='Конфіденційність', open='Відкрити Whenly', faq='Питання', privacy='Конфіденційність',
 q=['Whenly безкоштовний?','Чи потрібен акаунт?','Чи працює на телефоні?','Які мови підтримує Whenly?','Чим відрізняється від Doodle?','Чи можу я заповнити за когось іншого?','Хто бачить моє опитування?','Що відбувається з моїми даними?'],
 a=['Так. Whenly повністю безкоштовний і таким залишиться. Без платного доступу, без реклами.',
    'Ні. Акаунт нікому не потрібен, навіть тому, хто створює опитування. Вводите ім\'я і відмічаєте дні.',
    'Так. Whenly працює в будь-якому браузері і додається на головний екран як застосунок, без магазину.',
    'Двадцять три, серед них українська, англійська, французька, арабська, гінді, китайська, російська, тамазигт, курдська і шона. Мова береться з браузера, змінити її можна кнопкою з глобусом.',
    'Whenly не вимагає реєстрації, не показує реклами і безкоштовний. Ви відмічаєте дні в календарі, а світлофор показує, коли можуть усі.',
    'Так. Оберіть «Додати учасника», введіть ім\'я і відмітьте дні за цю людину.',
    'Будь-хто з посиланням. Посилання — довгий випадковий код, який неможливо вгадати, а сторінки опитувань не індексуються пошуковиками. Діліться посиланням лише зі своєю групою.',
    'Зберігаються лише назва, імена і відмічені дні, більше нічого. Без email, без телефону, без стеження. Ви контролюєте: будь-хто з посиланням може повністю видалити опитування, і тоді все зникає назавжди. Якщо ніхто не видалить, воно зберігається 12 місяців після останньої активності, щоб ви могли повернутися, а потім видаляється автоматично.'],
 h=['Що зберігає Whenly','Чого Whenly не робить','Хто бачить опитування','Як довго, і хто вирішує','Де, і запитання'],
 p=['Лише те, що ви самі вводите: назву опитування, імена учасників, відмічені дні і, за бажанням, час. Більше нічого. Без email, без телефону, без акаунта, без пароля.',
    'Без стеження, без реклами, без сторонніх cookie, без аналітики. Браузер локально запам\'ятовує лише мову, ім\'я і відкриті опитування, щоб не вводити нічого знову. Це залишається на вашому пристрої.',
    'Будь-хто з посиланням. Посилання — довгий випадковий код, який неможливо вгадати, а сторінки опитувань не індексуються пошуковиками; діліться посиланням лише зі своєю групою. Будь-хто з посиланням може також змінювати або видаляти імена і дні; коли хтось видаляє ім\'я, 30 днів видно коротку примітку, щоб група знала, що це не помилка застосунку.',
    'Ви. Поруч із назвою є «Повністю видалити це опитування». Натисніть (і підтвердьте) — назва, всі імена і всі відмічені дні зникнуть одразу і назавжди, для всіх. Якщо ніхто не видалить, опитування зберігається 12 місяців після останньої активності, щоб ви могли повернутися. Це не для збору даних; потім воно видаляється автоматично. Видалене ім\'я зникає назавжди через 30 днів.',
    'Дані зберігаються на серверах Cloudflare. Whenly має відкритий код; код і запитання — на GITHUB.'])

P['ru'] = dict(
 faq_title='Частые вопросы', priv_title='Конфиденциальность', open='Открыть Whenly', faq='Вопросы', privacy='Конфиденциальность',
 q=['Whenly бесплатный?','Нужен ли аккаунт?','Работает ли на телефоне?','Какие языки поддерживает Whenly?','Чем отличается от Doodle?','Могу ли я заполнить за другого?','Кто видит мой опрос?','Что происходит с моими данными?'],
 a=['Да. Whenly полностью бесплатный и таким останется. Без платного доступа, без рекламы.',
    'Нет. Аккаунт никому не нужен, даже тому, кто создаёт опрос. Вводите имя и отмечаете дни.',
    'Да. Whenly работает в любом браузере и добавляется на главный экран как приложение, без магазина.',
    'Двадцать три, среди них русский, английский, французский, арабский, хинди, китайский, тамазигт, курдский и шона. Язык берётся из браузера, сменить его можно кнопкой с глобусом.',
    'Whenly не требует регистрации, не показывает рекламу и бесплатен. Вы отмечаете дни в календаре, а светофор показывает, когда могут все.',
    'Да. Выберите «Добавить участника», введите имя и отметьте дни за этого человека.',
    'Любой, у кого есть ссылка. Ссылка — длинный случайный код, который нельзя угадать, а страницы опросов не индексируются поисковиками. Делитесь ссылкой только со своей группой.',
    'Хранятся только название, имена и отмеченные дни, больше ничего. Без email, без телефона, без слежки. Вы контролируете: любой со ссылкой может полностью удалить опрос, и тогда всё исчезает навсегда. Если никто не удалит, он хранится 12 месяцев после последней активности, чтобы вы могли вернуться, а потом удаляется автоматически.'],
 h=['Что хранит Whenly','Чего Whenly не делает','Кто видит опрос','Как долго, и кто решает','Где, и вопросы'],
 p=['Только то, что вы сами вводите: название опроса, имена участников, отмеченные дни и, по желанию, время. Больше ничего. Без email, без телефона, без аккаунта, без пароля.',
    'Без слежки, без рекламы, без сторонних cookie, без аналитики. Браузер локально запоминает только язык, имя и открытые опросы, чтобы не вводить ничего заново. Это остаётся на вашем устройстве.',
    'Любой, у кого есть ссылка. Ссылка — длинный случайный код, который нельзя угадать, а страницы опросов не индексируются поисковиками; делитесь ссылкой только со своей группой. Любой со ссылкой может также менять или удалять имена и дни; когда кто-то удаляет имя, 30 дней видна короткая заметка, чтобы группа знала, что это не ошибка приложения.',
    'Вы. Рядом с названием есть «Полностью удалить этот опрос». Нажмите (и подтвердите) — название, все имена и все отмеченные дни исчезнут сразу и навсегда, для всех. Если никто не удалит, опрос хранится 12 месяцев после последней активности, чтобы вы могли вернуться. Это не для сбора данных; потом он удаляется автоматически. Удалённое имя исчезает навсегда через 30 дней.',
    'Данные хранятся на серверах Cloudflare. Whenly с открытым кодом; код и вопросы — на GITHUB.'])

P['tr'] = dict(
 faq_title='Sık sorulan sorular', priv_title='Gizlilik', open='Whenly\'yi aç', faq='SSS', privacy='Gizlilik',
 q=['Whenly ücretsiz mi?','Hesap gerekli mi?','Telefonumda çalışır mı?','Whenly hangi dilleri destekler?','Doodle\'dan farkı ne?','Başkası için doldurabilir miyim?','Anketimi kim görebilir?','Verilerime ne olur?'],
 a=['Evet. Whenly tamamen ücretsizdir ve öyle kalır. Ödeme duvarı yok, reklam yok.',
    'Hayır. Kimsenin hesabı gerekmez, anketi oluşturanın bile. Adını yazarsın ve günlerini işaretlersin.',
    'Evet. Whenly her tarayıcıda çalışır ve uygulama gibi ana ekrana eklenebilir, mağaza gerekmez.',
    'Yirmi üç; Türkçe, İngilizce, Fransızca, Arapça, Hintçe, Çince, Rusça, Tamazight, Kürtçe ve Shona dahil. Dil tarayıcını takip eder ve küre düğmesiyle değiştirilir.',
    'Whenly kimseden kayıt istemez, reklam göstermez ve ücretsizdir. Takvimde günlere dokunursun, bir trafik ışığı herkesin ne zaman uygun olduğunu gösterir.',
    'Evet. "Katılımcı ekle"yi seç, bir ad yaz ve o kişi için günlere dokun.',
    'Bağlantıya sahip herkes. Bağlantı tahmin edilemeyen uzun, rastgele bir koddur ve anket sayfaları arama motorlarınca dizinlenmez. Bağlantıyı yalnızca grubunla paylaş.',
    'Yalnızca başlık, adlar ve işaretlenen günler saklanır, başka hiçbir şey. E-posta yok, telefon yok, izleme yok. Kontrol sende: bağlantıya sahip herkes anketi tamamen silebilir; o zaman her şey kalıcı olarak gider. Kimse silmezse, geri dönebilmen için son etkinlikten sonra 12 ay kalır, sonra otomatik silinir.'],
 h=['Whenly ne saklar','Whenly ne yapmaz','Bir anketi kim görebilir','Ne kadar süre ve kim karar verir','Nerede, ve sorular'],
 p=['Yalnızca kendi yazdıkların: anket başlığı, katılımcıların adları, işaretlenen günler ve isteğe bağlı bir saat. Başka hiçbir şey. E-posta yok, telefon yok, hesap yok, şifre yok.',
    'İzleme yok, reklam yok, üçüncü taraf çerezi yok, analitik yok. Tarayıcın yalnızca dilini, adını ve açtığın anketleri yerel olarak hatırlar; yeniden yazman gerekmesin diye. Bu, kendi cihazında kalır.',
    'Bağlantıya sahip herkes. Bağlantı tahmin edilemeyen uzun, rastgele bir koddur ve anket sayfaları arama motorlarınca dizinlenmez; bağlantıyı yalnızca grubunla paylaş. Bağlantıya sahip herkes adları ve günleri değiştirebilir veya kaldırabilir; biri bir adı kaldırdığında, grubun bunun uygulama hatası olmadığını bilmesi için 30 gün boyunca kısa bir not görünür.',
    'Sen. Başlığın yanında "Bu anketi tamamen sil" var. Tıkla (ve onayla); başlık, tüm adlar ve tüm işaretli günler herkes için anında ve kalıcı olarak silinir. Kimse silmezse anket, geri dönebilmen için son etkinlikten sonra 12 ay kalır. Bu veri toplamak için değildir; sonra otomatik silinir. Kaldırılan bir ad 30 gün sonra kalıcı olarak kaybolur.',
    'Veriler Cloudflare sunucularında saklanır. Whenly açık kaynaklıdır; kod ve sorular GITHUB\'da.'])

P['ar'] = dict(
 faq_title='الأسئلة الشائعة', priv_title='الخصوصية', open='افتح Whenly', faq='الأسئلة الشائعة', privacy='الخصوصية',
 q=['هل Whenly مجاني؟','هل أحتاج إلى حساب؟','هل يعمل على هاتفي؟','ما اللغات التي يدعمها Whenly؟','ما الفرق بينه وبين Doodle؟','هل يمكنني التعبئة نيابة عن شخص آخر؟','من يستطيع رؤية استطلاعي؟','ماذا يحدث لبياناتي؟'],
 a=['نعم. Whenly مجاني بالكامل وسيبقى كذلك. لا اشتراكات، لا إعلانات.',
    'لا. لا أحد يحتاج إلى حساب، ولا حتى من ينشئ الاستطلاع. تكتب اسمك وتحدد أيامك.',
    'نعم. يعمل Whenly في أي متصفح ويمكن إضافته إلى الشاشة الرئيسية كتطبيق، بلا متجر تطبيقات.',
    'ثلاث وعشرون لغة، منها العربية والإنجليزية والفرنسية والهندية والصينية والروسية والأمازيغية والكردية والشونا. تتبع لغة متصفحك ويمكن تغييرها من زر الكرة الأرضية.',
    'لا يطلب Whenly تسجيلاً من أحد، ولا يعرض إعلانات، وهو مجاني. تحدد الأيام في تقويم، وتظهر إشارة ملونة متى يكون الجميع متاحين.',
    'نعم. اختر «إضافة مشارك»، اكتب اسماً وحدد الأيام لذلك الشخص.',
    'كل من لديه الرابط. الرابط رمز عشوائي طويل لا يمكن تخمينه، وصفحات الاستطلاعات لا تُفهرسها محركات البحث. شارك الرابط مع مجموعتك فقط.',
    'يُحفظ فقط العنوان والأسماء والأيام المحددة، لا شيء غير ذلك. لا بريد إلكتروني، لا رقم هاتف، لا تتبع. أنت المتحكم: يمكن لأي شخص لديه الرابط حذف الاستطلاع نهائياً، فيختفي كل شيء إلى الأبد. وإن لم يحذفه أحد، يبقى 12 شهراً بعد آخر نشاط لتتمكن من العودة إليه، ثم يُحذف تلقائياً.'],
 h=['ما الذي يحفظه Whenly','ما الذي لا يفعله Whenly','من يستطيع رؤية الاستطلاع','لكم من الوقت، ومن يقرر','أين، والأسئلة'],
 p=['فقط ما تكتبه بنفسك: عنوان الاستطلاع، أسماء المشاركين، الأيام المحددة، ووقت اختياري. لا شيء غير ذلك. لا بريد إلكتروني، لا رقم هاتف، لا حساب، لا كلمة مرور.',
    'لا تتبع، لا إعلانات، لا ملفات تعريف ارتباط من جهات خارجية، لا تحليلات. يتذكر متصفحك محلياً فقط لغتك واسمك والاستطلاعات التي فتحتها حتى لا تعيد كتابة شيء. يبقى ذلك على جهازك.',
    'كل من لديه الرابط. الرابط رمز عشوائي طويل لا يمكن تخمينه، وصفحات الاستطلاعات لا تُفهرسها محركات البحث؛ فشارك الرابط مع مجموعتك فقط. يمكن لأي شخص لديه الرابط أيضاً تغيير الأسماء والأيام أو إزالتها؛ وعندما يزيل أحدهم اسماً، تبقى ملاحظة قصيرة ظاهرة 30 يوماً ليعرف الجميع أن ذلك ليس خطأً من التطبيق.',
    'أنت. بجانب العنوان يوجد «حذف هذا الاستطلاع نهائياً». اضغط عليه (وأكّد) فيختفي العنوان وكل الأسماء وكل الأيام المحددة فوراً وإلى الأبد، للجميع. وإن لم يحذفه أحد، يبقى الاستطلاع 12 شهراً بعد آخر نشاط لتتمكن من العودة إليه. ليس هذا لجمع البيانات؛ بعدها يُحذف تلقائياً. الاسم المُزال يختفي نهائياً بعد 30 يوماً.',
    'تُخزَّن البيانات على خوادم Cloudflare. ‏Whenly مفتوح المصدر؛ الشيفرة والأسئلة على GITHUB.'])

P['ur'] = dict(
 faq_title='عام سوالات', priv_title='رازداری', open='Whenly کھولیں', faq='سوالات', privacy='رازداری',
 q=['کیا Whenly مفت ہے؟','کیا مجھے اکاؤنٹ چاہیے؟','کیا یہ میرے فون پر چلتا ہے؟','Whenly کون سی زبانیں سپورٹ کرتا ہے؟','Doodle سے کیا فرق ہے؟','کیا میں کسی اور کے لیے بھر سکتا ہوں؟','میرا پول کون دیکھ سکتا ہے؟','میرے ڈیٹا کا کیا ہوتا ہے؟'],
 a=['ہاں۔ Whenly مکمل طور پر مفت ہے اور رہے گا۔ نہ کوئی ادائیگی، نہ اشتہار۔',
    'نہیں۔ کسی کو اکاؤنٹ نہیں چاہیے، پول بنانے والے کو بھی نہیں۔ اپنا نام لکھیں اور اپنے دن چنیں۔',
    'ہاں۔ Whenly ہر براؤزر میں چلتا ہے اور ایپ کی طرح ہوم اسکرین پر شامل ہو سکتا ہے، بغیر ایپ اسٹور کے۔',
    'تئیس زبانیں، جن میں اردو، انگریزی، فرانسیسی، عربی، ہندی، چینی، روسی، تمازیغت، کردی اور شونا شامل ہیں۔ زبان آپ کے براؤزر کے مطابق ہوتی ہے اور گلوب کے بٹن سے بدلی جا سکتی ہے۔',
    'Whenly کسی سے رجسٹریشن نہیں مانگتا، اشتہار نہیں دکھاتا اور مفت ہے۔ آپ کیلنڈر میں دن چنتے ہیں، اور ایک ٹریفک لائٹ دکھاتی ہے کہ سب کب آ سکتے ہیں۔',
    'ہاں۔ ”رکن شامل کریں“ چنیں، نام لکھیں اور اس شخص کے لیے دن چنیں۔',
    'جس کے پاس لنک ہے۔ لنک ایک لمبا بے ترتیب کوڈ ہے جس کا اندازہ نہیں لگایا جا سکتا، اور پول کے صفحات سرچ انجن میں شامل نہیں ہوتے۔ لنک صرف اپنے گروپ کے ساتھ شیئر کریں۔',
    'صرف عنوان، نام اور چنے ہوئے دن محفوظ ہوتے ہیں، اور کچھ نہیں۔ نہ ای میل، نہ فون نمبر، نہ ٹریکنگ۔ کنٹرول آپ کے پاس ہے: لنک والا کوئی بھی پول مکمل طور پر حذف کر سکتا ہے، اور پھر سب کچھ ہمیشہ کے لیے ختم ہو جاتا ہے۔ اگر کوئی حذف نہ کرے تو یہ آخری سرگرمی کے بعد 12 ماہ رہتا ہے تاکہ آپ واپس آ سکیں، پھر خود بخود حذف ہو جاتا ہے۔'],
 h=['Whenly کیا محفوظ کرتا ہے','Whenly کیا نہیں کرتا','پول کون دیکھ سکتا ہے','کتنی دیر، اور فیصلہ کون کرتا ہے','کہاں، اور سوالات'],
 p=['صرف وہ جو آپ خود لکھتے ہیں: پول کا عنوان، شرکاء کے نام، چنے ہوئے دن اور اختیاری وقت۔ اور کچھ نہیں۔ نہ ای میل، نہ فون نمبر، نہ اکاؤنٹ، نہ پاس ورڈ۔',
    'نہ ٹریکنگ، نہ اشتہار، نہ تیسرے فریق کی کوکیز، نہ اینالیٹکس۔ آپ کا براؤزر مقامی طور پر صرف آپ کی زبان، آپ کا نام اور کھولے گئے پول یاد رکھتا ہے تاکہ آپ کو دوبارہ کچھ نہ لکھنا پڑے۔ یہ آپ کے اپنے آلے پر رہتا ہے۔',
    'جس کے پاس لنک ہے۔ لنک ایک لمبا بے ترتیب کوڈ ہے جس کا اندازہ نہیں لگایا جا سکتا، اور پول کے صفحات سرچ انجن میں شامل نہیں ہوتے؛ لنک صرف اپنے گروپ کے ساتھ شیئر کریں۔ لنک والا کوئی بھی نام اور دن بدل یا ہٹا سکتا ہے؛ جب کوئی نام ہٹاتا ہے تو 30 دن تک ایک مختصر نوٹ نظر آتا ہے تاکہ گروپ کو معلوم ہو کہ یہ ایپ کی غلطی نہیں تھی۔',
    'آپ۔ عنوان کے ساتھ ”یہ پول مکمل طور پر حذف کریں“ ہے۔ اس پر کلک کریں (اور تصدیق کریں) تو عنوان، تمام نام اور تمام چنے ہوئے دن فوراً اور ہمیشہ کے لیے، سب کے لیے ختم ہو جاتے ہیں۔ اگر کوئی حذف نہ کرے تو پول آخری سرگرمی کے بعد 12 ماہ رہتا ہے تاکہ آپ واپس آ سکیں۔ یہ ڈیٹا جمع کرنے کے لیے نہیں ہے؛ اس کے بعد یہ خود بخود حذف ہو جاتا ہے۔ ہٹایا گیا نام 30 دن بعد ہمیشہ کے لیے غائب ہو جاتا ہے۔',
    'ڈیٹا Cloudflare کے سرورز پر رکھا جاتا ہے۔ Whenly اوپن سورس ہے؛ کوڈ اور سوالات GITHUB پر۔'])

P['hi'] = dict(
 faq_title='अक्सर पूछे जाने वाले सवाल', priv_title='गोपनीयता', open='Whenly खोलें', faq='सवाल', privacy='गोपनीयता',
 q=['क्या Whenly मुफ़्त है?','क्या मुझे अकाउंट चाहिए?','क्या यह मेरे फ़ोन पर चलता है?','Whenly कौन सी भाषाएँ सपोर्ट करता है?','Doodle से क्या फ़र्क़ है?','क्या मैं किसी और के लिए भर सकता हूँ?','मेरा पोल कौन देख सकता है?','मेरे डेटा का क्या होता है?'],
 a=['हाँ। Whenly पूरी तरह मुफ़्त है और रहेगा। कोई पेवॉल नहीं, कोई विज्ञापन नहीं।',
    'नहीं। किसी को अकाउंट नहीं चाहिए, पोल बनाने वाले को भी नहीं। अपना नाम लिखें और अपने दिन चुनें।',
    'हाँ। Whenly हर ब्राउज़र में चलता है और ऐप की तरह होम स्क्रीन पर जोड़ा जा सकता है, बिना ऐप स्टोर के।',
    'तेईस, जिनमें हिंदी, अंग्रेज़ी, फ़्रेंच, अरबी, चीनी, रूसी, तमाज़ीत, कुर्दिश और शोना शामिल हैं। भाषा आपके ब्राउज़र के अनुसार होती है और ग्लोब बटन से बदली जा सकती है।',
    'Whenly किसी से रजिस्ट्रेशन नहीं माँगता, विज्ञापन नहीं दिखाता और मुफ़्त है। आप कैलेंडर में दिन चुनते हैं, और एक ट्रैफ़िक लाइट दिखाती है कि सब कब आ सकते हैं।',
    'हाँ। "सदस्य जोड़ें" चुनें, नाम लिखें और उस व्यक्ति के लिए दिन चुनें।',
    'जिसके पास लिंक है। लिंक एक लंबा रैंडम कोड है जिसका अंदाज़ा नहीं लगाया जा सकता, और पोल के पेज सर्च इंजन में इंडेक्स नहीं होते। लिंक सिर्फ़ अपने ग्रुप के साथ शेयर करें।',
    'सिर्फ़ शीर्षक, नाम और चुने हुए दिन सहेजे जाते हैं, और कुछ नहीं। न ईमेल, न फ़ोन नंबर, न ट्रैकिंग। नियंत्रण आपके पास है: लिंक वाला कोई भी पोल को पूरी तरह हटा सकता है, और फिर सब कुछ हमेशा के लिए चला जाता है। अगर कोई नहीं हटाता, तो यह आख़िरी गतिविधि के 12 महीने बाद तक रहता है ताकि आप वापस आ सकें, फिर अपने आप हट जाता है।'],
 h=['Whenly क्या सहेजता है','Whenly क्या नहीं करता','पोल कौन देख सकता है','कितने समय तक, और फ़ैसला कौन करता है','कहाँ, और सवाल'],
 p=['सिर्फ़ वह जो आप ख़ुद लिखते हैं: पोल का शीर्षक, प्रतिभागियों के नाम, चुने हुए दिन और वैकल्पिक समय। और कुछ नहीं। न ईमेल, न फ़ोन नंबर, न अकाउंट, न पासवर्ड।',
    'न ट्रैकिंग, न विज्ञापन, न थर्ड-पार्टी कुकीज़, न एनालिटिक्स। आपका ब्राउज़र लोकल तौर पर सिर्फ़ आपकी भाषा, आपका नाम और खोले गए पोल याद रखता है ताकि आपको दोबारा कुछ न लिखना पड़े। यह आपके अपने डिवाइस पर रहता है।',
    'जिसके पास लिंक है। लिंक एक लंबा रैंडम कोड है जिसका अंदाज़ा नहीं लगाया जा सकता, और पोल के पेज सर्च इंजन में इंडेक्स नहीं होते; लिंक सिर्फ़ अपने ग्रुप के साथ शेयर करें। लिंक वाला कोई भी नाम और दिन बदल या हटा सकता है; जब कोई नाम हटाता है, तो 30 दिन तक एक छोटा नोट दिखता है ताकि ग्रुप को पता रहे कि यह ऐप की गलती नहीं थी।',
    'आप। शीर्षक के पास "यह पोल पूरी तरह हटाएँ" है। उस पर क्लिक करें (और पुष्टि करें) तो शीर्षक, सभी नाम और सभी चुने हुए दिन तुरंत और हमेशा के लिए, सबके लिए हट जाते हैं। अगर कोई नहीं हटाता, तो पोल आख़िरी गतिविधि के 12 महीने बाद तक रहता है ताकि आप वापस आ सकें। यह डेटा जमा करने के लिए नहीं है; उसके बाद यह अपने आप हट जाता है। हटाया गया नाम 30 दिन बाद हमेशा के लिए ग़ायब हो जाता है।',
    'डेटा Cloudflare के सर्वर पर रखा जाता है। Whenly ओपन सोर्स है; कोड और सवाल GITHUB पर।'])

P['bn'] = dict(
 faq_title='সচরাচর জিজ্ঞাসা', priv_title='গোপনীয়তা', open='Whenly খুলুন', faq='প্রশ্ন', privacy='গোপনীয়তা',
 q=['Whenly কি বিনামূল্যে?','আমার কি অ্যাকাউন্ট লাগবে?','এটা কি আমার ফোনে চলে?','Whenly কোন কোন ভাষা সাপোর্ট করে?','Doodle-এর সাথে পার্থক্য কী?','আমি কি অন্য কারো হয়ে পূরণ করতে পারি?','আমার পোল কে দেখতে পারে?','আমার ডেটার কী হয়?'],
 a=['হ্যাঁ। Whenly সম্পূর্ণ বিনামূল্যে এবং তা-ই থাকবে। কোনো পেওয়াল নেই, কোনো বিজ্ঞাপন নেই।',
    'না। কারো অ্যাকাউন্ট লাগে না, যে পোল তৈরি করে তারও না। আপনার নাম লিখুন আর দিন বেছে নিন।',
    'হ্যাঁ। Whenly যেকোনো ব্রাউজারে চলে এবং অ্যাপের মতো হোম স্ক্রিনে যোগ করা যায়, অ্যাপ স্টোর ছাড়াই।',
    'তেইশটি, যার মধ্যে বাংলা, ইংরেজি, ফরাসি, আরবি, হিন্দি, চীনা, রুশ, তামাজিঘত, কুর্দি ও শোনা আছে। ভাষা আপনার ব্রাউজার অনুযায়ী হয় এবং গ্লোব বোতামে বদলানো যায়।',
    'Whenly কাউকে নিবন্ধন করতে বলে না, বিজ্ঞাপন দেখায় না এবং বিনামূল্যে। আপনি ক্যালেন্ডারে দিন বাছেন, আর একটি ট্রাফিক লাইট দেখায় কখন সবাই পারবে।',
    'হ্যাঁ। "সদস্য যোগ করুন" বেছে নিন, একটি নাম লিখুন এবং সেই ব্যক্তির জন্য দিন বাছুন।',
    'যার কাছে লিংক আছে। লিংকটি একটি লম্বা এলোমেলো কোড যা অনুমান করা যায় না, আর পোলের পাতা সার্চ ইঞ্জিনে সূচিবদ্ধ হয় না। লিংক শুধু আপনার দলের সাথে শেয়ার করুন।',
    'শুধু শিরোনাম, নাম আর বাছাই করা দিন সংরক্ষিত হয়, আর কিছু না। কোনো ইমেইল, ফোন নম্বর বা ট্র্যাকিং নেই। নিয়ন্ত্রণ আপনার হাতে: লিংক থাকা যে কেউ পোলটি সম্পূর্ণ মুছে ফেলতে পারে, তখন সব চিরতরে চলে যায়। কেউ না মুছলে এটি শেষ কার্যকলাপের পর ১২ মাস থাকে যাতে আপনি ফিরে আসতে পারেন, তারপর নিজে থেকে মুছে যায়।'],
 h=['Whenly কী সংরক্ষণ করে','Whenly কী করে না','পোল কে দেখতে পারে','কতদিন, আর কে ঠিক করে','কোথায়, আর প্রশ্ন'],
 p=['শুধু আপনি নিজে যা লেখেন: পোলের শিরোনাম, অংশগ্রহণকারীদের নাম, বাছাই করা দিন আর ঐচ্ছিক সময়। আর কিছু না। কোনো ইমেইল, ফোন নম্বর, অ্যাকাউন্ট বা পাসওয়ার্ড নেই।',
    'কোনো ট্র্যাকিং, বিজ্ঞাপন, তৃতীয় পক্ষের কুকি বা অ্যানালিটিক্স নেই। আপনার ব্রাউজার স্থানীয়ভাবে শুধু আপনার ভাষা, নাম আর খোলা পোলগুলো মনে রাখে যাতে আবার কিছু লিখতে না হয়। সেটা আপনার নিজের ডিভাইসেই থাকে।',
    'যার কাছে লিংক আছে। লিংকটি একটি লম্বা এলোমেলো কোড যা অনুমান করা যায় না, আর পোলের পাতা সার্চ ইঞ্জিনে সূচিবদ্ধ হয় না; লিংক শুধু আপনার দলের সাথে শেয়ার করুন। লিংক থাকা যে কেউ নাম ও দিন বদলাতে বা সরাতে পারে; কেউ নাম সরালে ৩০ দিন একটি ছোট নোট দেখা যায় যাতে দল জানে এটা অ্যাপের ভুল নয়।',
    'আপনি। শিরোনামের পাশে "এই পোল সম্পূর্ণ মুছে ফেলুন" আছে। সেটিতে ক্লিক করুন (আর নিশ্চিত করুন), তাহলে শিরোনাম, সব নাম আর সব বাছাই করা দিন সঙ্গে সঙ্গে ও চিরতরে সবার জন্য মুছে যায়। কেউ না মুছলে পোলটি শেষ কার্যকলাপের পর ১২ মাস থাকে যাতে আপনি ফিরে আসতে পারেন। এটা ডেটা সংগ্রহের জন্য নয়; তারপর এটি নিজে থেকে মুছে যায়। সরানো নাম ৩০ দিন পর চিরতরে চলে যায়।',
    'ডেটা Cloudflare-এর সার্ভারে রাখা হয়। Whenly ওপেন সোর্স; কোড আর প্রশ্ন GITHUB-এ।'])

P['id'] = dict(
 faq_title='Pertanyaan umum', priv_title='Privasi', open='Buka Whenly', faq='FAQ', privacy='Privasi',
 q=['Apakah Whenly gratis?','Apakah saya perlu akun?','Apakah bisa di ponsel saya?','Bahasa apa saja yang didukung Whenly?','Apa bedanya dengan Doodle?','Bisakah saya mengisi untuk orang lain?','Siapa yang bisa melihat polling saya?','Apa yang terjadi dengan data saya?'],
 a=['Ya. Whenly sepenuhnya gratis dan tetap gratis. Tanpa paywall, tanpa iklan.',
    'Tidak. Tak seorang pun perlu akun, bahkan pembuat polling. Ketik nama kamu dan pilih hari kamu.',
    'Ya. Whenly berjalan di semua browser dan bisa ditambahkan ke layar utama seperti aplikasi, tanpa app store.',
    'Dua puluh tiga, termasuk Indonesia, Inggris, Prancis, Arab, Hindi, Mandarin, Rusia, Tamazight, Kurdi, dan Shona. Bahasa mengikuti browser kamu dan bisa diganti lewat tombol globe.',
    'Whenly tidak minta siapa pun mendaftar, tidak menampilkan iklan, dan gratis. Kamu memilih hari di kalender, dan lampu lalu lintas menunjukkan kapan semua orang bisa.',
    'Ya. Pilih "Tambah peserta", ketik nama, lalu pilih hari untuk orang itu.',
    'Siapa pun yang punya tautannya. Tautan adalah kode acak panjang yang tak bisa ditebak, dan halaman polling tidak diindeks mesin pencari. Bagikan tautan hanya ke grup kamu.',
    'Hanya judul, nama, dan hari yang dipilih yang disimpan, tidak ada yang lain. Tanpa email, tanpa nomor telepon, tanpa pelacakan. Kendali ada di kamu: siapa pun dengan tautan bisa menghapus polling sepenuhnya, dan semuanya hilang selamanya. Jika tak ada yang menghapus, polling disimpan 12 bulan setelah aktivitas terakhir supaya kamu bisa kembali, lalu dihapus otomatis.'],
 h=['Apa yang disimpan Whenly','Apa yang tidak dilakukan Whenly','Siapa yang bisa melihat polling','Berapa lama, dan siapa yang memutuskan','Di mana, dan pertanyaan'],
 p=['Hanya yang kamu ketik sendiri: judul polling, nama peserta, hari yang dipilih, dan jam (opsional). Tidak ada yang lain. Tanpa email, tanpa nomor telepon, tanpa akun, tanpa kata sandi.',
    'Tanpa pelacakan, tanpa iklan, tanpa cookie pihak ketiga, tanpa analitik. Browser kamu hanya mengingat secara lokal bahasa, nama, dan polling yang kamu buka, agar kamu tak perlu mengetik ulang. Itu tetap di perangkat kamu.',
    'Siapa pun yang punya tautannya. Tautan adalah kode acak panjang yang tak bisa ditebak, dan halaman polling tidak diindeks mesin pencari; bagikan tautan hanya ke grup kamu. Siapa pun dengan tautan juga bisa mengubah atau menghapus nama dan hari; saat seseorang menghapus nama, catatan singkat tetap terlihat 30 hari agar grup tahu itu bukan kesalahan aplikasi.',
    'Kamu. Di samping judul ada "Hapus polling ini sepenuhnya". Klik (dan konfirmasi), maka judul, semua nama, dan semua hari yang dipilih langsung hilang selamanya, untuk semua orang. Jika tak ada yang menghapus, polling disimpan 12 bulan setelah aktivitas terakhir supaya kamu bisa kembali. Ini bukan untuk mengumpulkan data; setelah itu dihapus otomatis. Nama yang dihapus hilang selamanya setelah 30 hari.',
    'Data disimpan di server Cloudflare. Whenly open source; kode dan pertanyaan ada di GITHUB.'])

P['vi'] = dict(
 faq_title='Câu hỏi thường gặp', priv_title='Quyền riêng tư', open='Mở Whenly', faq='Hỏi đáp', privacy='Quyền riêng tư',
 q=['Whenly có miễn phí không?','Tôi có cần tài khoản không?','Có chạy trên điện thoại không?','Whenly hỗ trợ những ngôn ngữ nào?','Khác gì so với Doodle?','Tôi có thể điền giúp người khác không?','Ai có thể xem bình chọn của tôi?','Dữ liệu của tôi sẽ ra sao?'],
 a=['Có. Whenly hoàn toàn miễn phí và sẽ luôn như vậy. Không thu phí, không quảng cáo.',
    'Không. Không ai cần tài khoản, kể cả người tạo bình chọn. Bạn nhập tên và chọn ngày.',
    'Có. Whenly chạy trên mọi trình duyệt và có thể thêm vào màn hình chính như một ứng dụng, không cần cửa hàng ứng dụng.',
    'Hai mươi ba, gồm tiếng Việt, Anh, Pháp, Ả Rập, Hindi, Trung, Nga, Tamazight, Kurd và Shona. Ngôn ngữ theo trình duyệt của bạn và đổi được bằng nút quả địa cầu.',
    'Whenly không yêu cầu ai đăng ký, không hiển thị quảng cáo và miễn phí. Bạn chọn ngày trên lịch, và một đèn giao thông cho biết khi nào mọi người đều rảnh.',
    'Có. Chọn "Thêm người tham gia", nhập tên và chọn ngày cho người đó.',
    'Bất kỳ ai có liên kết. Liên kết là một mã ngẫu nhiên dài không thể đoán, và trang bình chọn không được công cụ tìm kiếm lập chỉ mục. Chỉ chia sẻ liên kết với nhóm của bạn.',
    'Chỉ tiêu đề, tên và các ngày đã chọn được lưu, không gì khác. Không email, không số điện thoại, không theo dõi. Bạn nắm quyền: ai có liên kết cũng có thể xóa hoàn toàn bình chọn, và mọi thứ biến mất vĩnh viễn. Nếu không ai xóa, bình chọn được giữ 12 tháng sau hoạt động cuối để bạn có thể quay lại, rồi tự động bị xóa.'],
 h=['Whenly lưu gì','Whenly không làm gì','Ai có thể xem bình chọn','Bao lâu, và ai quyết định','Ở đâu, và câu hỏi'],
 p=['Chỉ những gì bạn tự nhập: tiêu đề bình chọn, tên người tham gia, các ngày đã chọn và giờ (tùy chọn). Không gì khác. Không email, không số điện thoại, không tài khoản, không mật khẩu.',
    'Không theo dõi, không quảng cáo, không cookie bên thứ ba, không phân tích. Trình duyệt của bạn chỉ ghi nhớ cục bộ ngôn ngữ, tên và các bình chọn bạn đã mở, để bạn không phải nhập lại. Điều đó ở lại trên thiết bị của bạn.',
    'Bất kỳ ai có liên kết. Liên kết là một mã ngẫu nhiên dài không thể đoán, và trang bình chọn không được công cụ tìm kiếm lập chỉ mục; chỉ chia sẻ liên kết với nhóm của bạn. Ai có liên kết cũng có thể đổi hoặc xóa tên và ngày; khi ai đó xóa một tên, một ghi chú ngắn hiện trong 30 ngày để nhóm biết đó không phải lỗi của ứng dụng.',
    'Bạn. Cạnh tiêu đề có "Xóa hoàn toàn bình chọn này". Bấm vào (và xác nhận), tiêu đề, mọi tên và mọi ngày đã chọn sẽ biến mất ngay lập tức và vĩnh viễn, với tất cả mọi người. Nếu không ai xóa, bình chọn được giữ 12 tháng sau hoạt động cuối để bạn có thể quay lại. Không phải để thu thập dữ liệu; sau đó nó tự động bị xóa. Tên đã xóa biến mất vĩnh viễn sau 30 ngày.',
    'Dữ liệu được lưu trên máy chủ Cloudflare. Whenly là mã nguồn mở; mã nguồn và câu hỏi ở GITHUB.'])

P['zh'] = dict(
 faq_title='常见问题', priv_title='隐私', open='打开 Whenly', faq='常见问题', privacy='隐私',
 q=['Whenly 免费吗？','需要账号吗？','手机上能用吗？','Whenly 支持哪些语言？','和 Doodle 有什么区别？','可以替别人填写吗？','谁能看到我的投票？','我的数据会怎样？'],
 a=['免费。Whenly 完全免费，并将一直免费。没有付费墙，没有广告。',
    '不需要。任何人都不需要账号，创建投票的人也不需要。输入名字，点选日子即可。',
    '可以。Whenly 在任何浏览器中都能用，还能像应用一样添加到主屏幕，无需应用商店。',
    '二十三种，包括中文、英语、法语、阿拉伯语、印地语、俄语、塔马齐格特语、库尔德语和绍纳语。语言跟随浏览器设置，可用地球按钮切换。',
    'Whenly 不要求任何人注册，不显示广告，而且免费。你在日历上点选日子，红绿灯会显示大家什么时候都可以。',
    '可以。选择"添加参与者"，输入名字，然后替那个人点选日子。',
    '任何拥有链接的人。链接是一段无法猜到的长随机码，投票页面也不会被搜索引擎收录。请只把链接分享给你的群组。',
    '只保存标题、名字和点选的日子，其他一概不存。没有邮箱，没有手机号，没有追踪。你说了算：任何拥有链接的人都可以彻底删除投票，之后一切永久消失。如果没人删除，投票会在最后一次活动后保留 12 个月，方便你回来查看，之后自动删除。'],
 h=['Whenly 保存什么','Whenly 不做什么','谁能看到投票','保留多久，谁决定','存在哪里，以及问题'],
 p=['只保存你自己输入的内容：投票标题、参与者名字、点选的日子和可选的时间。其他一概不存。没有邮箱，没有手机号，没有账号，没有密码。',
    '没有追踪，没有广告，没有第三方 Cookie，没有分析统计。浏览器只在本地记住你的语言、名字和打开过的投票，免得你重复输入。这些都留在你自己的设备上。',
    '任何拥有链接的人。链接是一段无法猜到的长随机码，投票页面也不会被搜索引擎收录，所以请只把链接分享给你的群组。拥有链接的人也可以修改或移除名字和日子；有人移除名字时，会显示一条简短提示 30 天，让大家知道这不是应用出错。',
    '你决定。标题旁边有"彻底删除这个投票"。点击（并确认）后，标题、所有名字和所有点选的日子会立即永久删除，对所有人都是如此。如果没人删除，投票会在最后一次活动后保留 12 个月，方便你回来查看。这不是为了收集数据；之后会自动删除。被移除的名字在 30 天后永久消失。',
    '数据存储在 Cloudflare 的服务器上。Whenly 是开源的；代码和问题请见 GITHUB。'])

P['ja'] = dict(
 faq_title='よくある質問', priv_title='プライバシー', open='Whenly を開く', faq='よくある質問', privacy='プライバシー',
 q=['Whenly は無料ですか？','アカウントは必要ですか？','スマホでも使えますか？','対応している言語は？','Doodle との違いは？','他の人の分も入力できますか？','誰が日程調整を見られますか？','データはどうなりますか？'],
 a=['はい。Whenly は完全に無料で、これからも無料です。有料化も広告もありません。',
    'いいえ。作成する人も含めて、誰もアカウントは必要ありません。名前を入力して日をタップするだけです。',
    'はい。どのブラウザでも動き、アプリのようにホーム画面に追加できます。アプリストアは不要です。',
    '23 言語。日本語、英語、フランス語、アラビア語、ヒンディー語、中国語、ロシア語、タマジクト語、クルド語、ショナ語などです。ブラウザの言語に合わせて表示され、地球のボタンで切り替えられます。',
    'Whenly は登録を求めず、広告を出さず、無料です。カレンダーで日をタップすると、信号機の色で全員が参加できる日がわかります。',
    'はい。「参加者を追加」を選び、名前を入力して、その人の分の日をタップします。',
    'リンクを知っている人全員です。リンクは推測できない長いランダムなコードで、日程調整のページは検索エンジンに登録されません。リンクはグループ内だけで共有してください。',
    '保存するのはタイトル、名前、タップした日だけです。メールアドレスも電話番号も追跡もありません。決めるのはあなたです。リンクを知っている人は誰でも日程調整を完全に削除でき、すべてが永久に消えます。誰も削除しなければ、後で戻れるように最後の操作から 12 か月保存され、その後自動的に削除されます。'],
 h=['Whenly が保存するもの','Whenly がしないこと','誰が見られるか','保存期間と、誰が決めるか','保存場所と、質問'],
 p=['あなたが入力したものだけです。日程調整のタイトル、参加者の名前、タップした日、任意の時刻。それ以外は何も保存しません。メールアドレス、電話番号、アカウント、パスワードはありません。',
    '追跡なし、広告なし、サードパーティ Cookie なし、アクセス解析なし。ブラウザは言語、名前、開いた日程調整だけを端末内に記憶し、再入力の手間を省きます。それはあなたの端末の中だけにあります。',
    'リンクを知っている人全員です。リンクは推測できない長いランダムなコードで、ページは検索エンジンに登録されないので、リンクはグループ内だけで共有してください。リンクを知っている人は名前や日を変更・削除することもできます。誰かが名前を削除すると、アプリの不具合ではないとわかるように、短いメモが 30 日間表示されます。',
    'あなたです。タイトルの横に「この日程調整を完全に削除」があります。押して確認すると、タイトル、すべての名前、すべてのタップした日が全員にとって即座に永久に消えます。誰も削除しなければ、後で戻れるように最後の操作から 12 か月保存されます。データ収集のためではなく、その後は自動的に削除されます。削除された名前は 30 日後に完全に消えます。',
    'データは Cloudflare のサーバーに保存されます。Whenly はオープンソースです。コードと質問は GITHUB へ。'])

P['ko'] = dict(
 faq_title='자주 묻는 질문', priv_title='개인정보', open='Whenly 열기', faq='자주 묻는 질문', privacy='개인정보',
 q=['Whenly는 무료인가요?','계정이 필요한가요?','휴대폰에서도 되나요?','어떤 언어를 지원하나요?','Doodle과 뭐가 다른가요?','다른 사람 대신 입력할 수 있나요?','내 투표는 누가 볼 수 있나요?','내 데이터는 어떻게 되나요?'],
 a=['네. Whenly는 완전히 무료이고 앞으로도 무료예요. 유료 전환도 광고도 없어요.',
    '아니요. 투표를 만드는 사람을 포함해 아무도 계정이 필요 없어요. 이름을 쓰고 날짜를 누르면 돼요.',
    '네. 어떤 브라우저에서도 되고, 앱처럼 홈 화면에 추가할 수 있어요. 앱 스토어는 필요 없어요.',
    '23개 언어예요. 한국어, 영어, 프랑스어, 아랍어, 힌디어, 중국어, 러시아어, 타마지트어, 쿠르드어, 쇼나어 등이 있어요. 브라우저 언어를 따르고, 지구본 버튼으로 바꿀 수 있어요.',
    'Whenly는 가입을 요구하지 않고, 광고가 없고, 무료예요. 달력에서 날짜를 누르면 신호등이 모두 가능한 날을 보여줘요.',
    '네. "참여자 추가"를 고르고 이름을 쓴 다음, 그 사람 대신 날짜를 누르세요.',
    '링크가 있는 누구나요. 링크는 추측할 수 없는 긴 무작위 코드이고, 투표 페이지는 검색 엔진에 등록되지 않아요. 링크는 그룹 안에서만 공유하세요.',
    '제목, 이름, 누른 날짜만 저장되고 그 외에는 아무것도 저장하지 않아요. 이메일도, 전화번호도, 추적도 없어요. 결정은 당신 몫이에요. 링크가 있는 누구나 투표를 완전히 삭제할 수 있고, 그러면 모든 것이 영구히 사라져요. 아무도 삭제하지 않으면 다시 돌아올 수 있도록 마지막 활동 후 12개월 동안 보관되고, 그 뒤 자동으로 삭제돼요.'],
 h=['Whenly가 저장하는 것','Whenly가 하지 않는 것','투표를 볼 수 있는 사람','얼마나 오래, 누가 결정하나','어디에, 그리고 문의'],
 p=['직접 입력한 것만이에요. 투표 제목, 참여자 이름, 누른 날짜, 그리고 선택 사항인 시간. 그 외에는 없어요. 이메일, 전화번호, 계정, 비밀번호 모두 없어요.',
    '추적 없음, 광고 없음, 제3자 쿠키 없음, 분석 도구 없음. 브라우저는 다시 입력하지 않도록 언어, 이름, 열어본 투표만 기기 안에 기억해요. 그건 당신 기기에만 남아요.',
    '링크가 있는 누구나요. 링크는 추측할 수 없는 긴 무작위 코드이고, 투표 페이지는 검색 엔진에 등록되지 않으니 링크는 그룹 안에서만 공유하세요. 링크가 있는 사람은 이름과 날짜를 바꾸거나 지울 수도 있어요. 누군가 이름을 지우면, 앱 오류가 아니라는 걸 그룹이 알 수 있도록 짧은 안내가 30일 동안 보여요.',
    '당신이요. 제목 옆에 "이 투표 완전히 삭제"가 있어요. 누르고 확인하면 제목, 모든 이름, 모든 날짜가 모두에게 즉시, 영구히 사라져요. 아무도 삭제하지 않으면 다시 돌아올 수 있도록 마지막 활동 후 12개월 보관돼요. 데이터를 모으려는 게 아니라서, 그 뒤엔 자동으로 삭제돼요. 지운 이름은 30일 뒤 영구히 사라져요.',
    '데이터는 Cloudflare 서버에 저장돼요. Whenly는 오픈 소스이고, 코드와 문의는 GITHUB에서요.'])

P['sw'] = dict(
 faq_title='Maswali yanayoulizwa mara kwa mara', priv_title='Faragha', open='Fungua Whenly', faq='Maswali', privacy='Faragha',
 q=['Je, Whenly ni bure?','Je, ninahitaji akaunti?','Je, inafanya kazi kwenye simu yangu?','Whenly inatumia lugha zipi?','Tofauti na Doodle ni nini?','Naweza kujaza kwa niaba ya mtu mwingine?','Nani anaweza kuona kura yangu?','Data yangu inakuwaje?'],
 a=['Ndiyo. Whenly ni bure kabisa na itabaki bure. Hakuna malipo, hakuna matangazo.',
    'Hapana. Hakuna anayehitaji akaunti, hata anayetengeneza kura. Unaandika jina lako na kuchagua siku zako.',
    'Ndiyo. Whenly inafanya kazi kwenye kivinjari chochote na inaweza kuongezwa kwenye skrini ya mwanzo kama programu, bila duka la programu.',
    'Ishirini na tatu, zikiwemo Kiswahili, Kiingereza, Kifaransa, Kiarabu, Kihindi, Kichina, Kirusi, Tamazight, Kikurdi na Kishona. Lugha inafuata kivinjari chako na inaweza kubadilishwa kwa kitufe cha dunia.',
    'Whenly haiombi mtu kujisajili, haionyeshi matangazo na ni bure. Unabofya siku kwenye kalenda, na taa ya barabarani inaonyesha wakati kila mtu anaweza.',
    'Ndiyo. Chagua "Ongeza mshiriki", andika jina na ubofye siku kwa niaba ya mtu huyo.',
    'Yeyote mwenye kiungo. Kiungo ni msimbo mrefu wa nasibu usioweza kukisiwa, na kurasa za kura hazionyeshwi na injini za utafutaji. Shiriki kiungo na kikundi chako tu.',
    'Ni kichwa, majina na siku zilizochaguliwa tu ndizo huhifadhiwa, hakuna kingine. Hakuna barua pepe, hakuna nambari ya simu, hakuna ufuatiliaji. Udhibiti ni wako: yeyote mwenye kiungo anaweza kufuta kura kabisa, na kila kitu kinatoweka milele. Kama hakuna anayeifuta, inabaki miezi 12 baada ya shughuli ya mwisho ili uweze kurudi, kisha inafutwa kiotomatiki.'],
 h=['Whenly inahifadhi nini','Whenly haifanyi nini','Nani anaweza kuona kura','Kwa muda gani, na nani anaamua','Wapi, na maswali'],
 p=['Ni yale unayoandika mwenyewe tu: kichwa cha kura, majina ya washiriki, siku zilizochaguliwa na saa ya hiari. Hakuna kingine. Hakuna barua pepe, hakuna nambari ya simu, hakuna akaunti, hakuna nenosiri.',
    'Hakuna ufuatiliaji, hakuna matangazo, hakuna vidakuzi vya wahusika wengine, hakuna uchanganuzi. Kivinjari chako kinakumbuka tu kwenye kifaa lugha yako, jina lako na kura ulizofungua, ili usiandike tena. Hiyo inabaki kwenye kifaa chako.',
    'Yeyote mwenye kiungo. Kiungo ni msimbo mrefu wa nasibu usioweza kukisiwa, na kurasa za kura hazionyeshwi na injini za utafutaji; shiriki kiungo na kikundi chako tu. Yeyote mwenye kiungo anaweza pia kubadilisha au kuondoa majina na siku; mtu akiondoa jina, taarifa fupi inabaki siku 30 ili kikundi kijue haikuwa hitilafu ya programu.',
    'Wewe. Kando ya kichwa kuna "Futa kura hii kabisa". Bofya (na uthibitishe), na kichwa, majina yote na siku zote zilizochaguliwa zinatoweka mara moja na milele, kwa kila mtu. Kama hakuna anayeifuta, kura inabaki miezi 12 baada ya shughuli ya mwisho ili uweze kurudi. Hii si kwa ajili ya kukusanya data; baada ya hapo inafutwa kiotomatiki. Jina lililoondolewa linatoweka milele baada ya siku 30.',
    'Data inahifadhiwa kwenye seva za Cloudflare. Whenly ni chanzo huria; msimbo na maswali yako GITHUB.'])

P['zgh'] = dict(
 faq_title='ⵉⵙⵇⵙⵉⵜⵏ ⵉⵎⵢⴰⵍⵍⴰⵏ', priv_title='ⵜⵓⴷⵔⵜ ⵜⵓⵙⵍⵉⴳⵜ', open='ⵕⵥⵎ Whenly', faq='ⵉⵙⵇⵙⵉⵜⵏ', privacy='ⵜⵓⴷⵔⵜ ⵜⵓⵙⵍⵉⴳⵜ',
 q=['ⵉⵙ ⵉⴳⴰ Whenly ⴱⴰⵟⵍ?','ⵉⵙ ⵙⵙⵉⵔⵉⴷⵖ ⴰⵎⵉⴹⴰⵏ?','ⵉⵙ ⵉⵜⵜⵓⵙⵎⵔⴰⵙ ⴳ ⵓⵜⵉⵍⵉⴼⵓⵏ ⵉⵏⵓ?','ⵎⴰⵏ ⵜⵓⵜⵍⴰⵢⵉⵏ ⴰⴷ ⵉⵍⵍⴰⵏ ⴳ Whenly?','ⵎⴰ ⴷ ⴰⵎⵣⴰⵔⴰⵢ ⴷ Doodle?','ⵉⵙ ⵣⵎⵔⵖ ⴰⴷ ⵙⵎⴷⵖ ⵉ ⵢⴰⵏ ⵢⴰⴹⵏ?','ⵎⴰ ⵉⵣⵎⵔⵏ ⴰⴷ ⵉⵥⵕ ⴰⵎⵙⴰⴳⴰⵔ ⵉⵏⵓ?','ⵎⴰ ⵉⵜⵜⵉⵍⵉⵏ ⵉ ⵉⵙⴼⴽⴰ ⵉⵏⵓ?'],
 a=['ⵢⴰⵀ. Whenly ⵉⴳⴰ ⴱⴰⵟⵍ ⵙ ⵓⵎⴰⵜⴰ ⴷ ⴰⴷ ⵉⵇⵇⵉⵎ ⴱⴰⵟⵍ. ⴱⵍⴰ ⴰⴼⵔⴰ, ⴱⵍⴰ ⵉⵙⴷⴰⵡⵏ.',
    'ⵓⵀⵓ. ⵓⵔ ⵉⵙⵙⵉⵔⵉⴷ ⵢⴰⵏ ⴰⵎⵉⴹⴰⵏ, ⵓⵍⴰ ⵡⴰⵏⵏⴰ ⵉⵙⴽⴰⵔⵏ ⴰⵎⵙⴰⴳⴰⵔ. ⵜⴰⵔⴰⴷ ⵉⵙⵎ ⵏⵏⴽ, ⵜⵙⵜⵉⴷ ⵓⵙⵙⴰⵏ ⵏⵏⴽ.',
    'ⵢⴰⵀ. Whenly ⴰⵔ ⵉⵜⵜⵓⵙⵎⵔⴰⵙ ⴳ ⴽⵓ ⴰⵎⵙⵙⴰⵔⴰ, ⵜⵣⵎⵔⴷ ⴰⴷ ⵜ ⵜⵔⵏⵓⴷ ⵖⵔ ⵓⴳⴷⵉⵍ ⴰⵎⵣⵡⴰⵔⵓ ⴰⵎ ⵜⵙⵏⵙⵉ, ⴱⵍⴰ ⵜⴰⵃⴰⵏⵓⵜ ⵏ ⵜⵙⵏⵙⵉⵡⵉⵏ.',
    'ⵙⵉⵏ ⴷ ⵎⵔⴰⵡ ⴷ ⴽⵕⴰⴹ, ⴳⵉⵙⵏⵜ ⵜⴰⵎⴰⵣⵉⵖⵜ, ⵜⴰⵏⴳⵍⵉⵣⵜ, ⵜⴰⴼⵕⴰⵏⵙⵉⵙⵜ, ⵜⴰⵄⵕⴰⴱⵜ, ⵜⴰⵀⵉⵏⴷⵉⵜ, ⵜⴰⵛⵉⵏⵡⵉⵜ, ⵜⴰⵔⵓⵙⵉⵜ, ⵜⴰⴽⵓⵔⴷⵉⵜ ⴷ ⵜⴰⵛⵓⵏⴰⵜ. ⵜⵓⵜⵍⴰⵢⵜ ⴰⵔ ⵜⴹⴼⴰⵕ ⴰⵎⵙⵙⴰⵔⴰ ⵏⵏⴽ, ⵜⵣⵎⵔⴷ ⴰⴷ ⵜⵜ ⵜⵙⵏⴼⵍⴷ ⵙ ⵜⴰⵏⴰⵙⵜ ⵏ ⵓⵎⴰⴹⴰⵍ.',
    'Whenly ⵓⵔ ⵉⵙⵙⵓⵜⵓⵔ ⵉ ⵢⴰⵏ ⴰⴷ ⵉⵙⵙⵓⴷⵓ, ⵓⵔ ⵉⵎⵎⴰⵍ ⵉⵙⴷⴰⵡⵏ, ⵉⴳⴰ ⴱⴰⵟⵍ. ⵜⵙⵜⴰⵢⴷ ⵓⵙⵙⴰⵏ ⴳ ⵓⵙⵎⵀⴰⵍ, ⴷ ⵢⴰⵜ ⵜⴼⴰⵡⵜ ⴰⵔ ⵜⵎⵎⴰⵍ ⵎⴰⵏⴰⴳ ⵣⵎⵔⵏ ⴽⵓ ⵢⴰⵏ.',
    'ⵢⴰⵀ. ⵙⵜⵉ «ⵔⵏⵓ ⴰⵎⴷⵔⴰⵡ», ⴰⵔⴰ ⵉⵙⵎ, ⵙⵜⵉ ⵓⵙⵙⴰⵏ ⵉ ⵓⴼⴳⴰⵏ ⴰⵏⵏ.',
    'ⴽⵓ ⵢⴰⵏ ⴷⴰⵔ ⵉⵍⵍⴰ ⵓⵙⵖⵏ. ⴰⵙⵖⵏ ⵉⴳⴰ ⵢⴰⵜ ⵜⵏⴳⴰⵍⵜ ⵜⴰⵖⵣⵣⴰⴼⵜ ⵓⵔ ⵉⵣⵎⵔⵏ ⵢⴰⵏ ⴰⴷ ⵜⵜ ⵢⴰⴼ, ⴷ ⵜⴰⵙⵏⵉⵡⵉⵏ ⵏ ⵉⵎⵙⴰⴳⴰⵔⵏ ⵓⵔ ⵜⵜⵉⵍⵉⵏⵜ ⴳ ⵉⵎⵙⵙⵓⴼⵖⵏ ⵏ ⵓⵔⵣⵣⵓ. ⴱⴹⵓ ⴰⵙⵖⵏ ⵖⴰⵙ ⴷ ⵜⵔⴰⴱⴱⵓⵜ ⵏⵏⴽ.',
    'ⴰⵔ ⵉⵜⵜⵓⵃⴹⴰ ⵖⴰⵙ ⵓⵣⵡⵍ, ⵉⵙⵎⴰⵡⵏ ⴷ ⵡⵓⵙⵙⴰⵏ ⵉⵜⵜⵓⵙⵜⴰⵢⵏ, ⵡⴰⵍⵓ ⵢⴰⴹⵏ. ⴱⵍⴰ ⵉⵎⴰⵢⵍ, ⴱⵍⴰ ⵓⵟⵟⵓⵏ ⵏ ⵓⵜⵉⵍⵉⴼⵓⵏ, ⴱⵍⴰ ⴰⴹⴼⴰⵕ. ⴰⴹⵓⴼ ⵉⴳⴰ ⵡⵉⵏⵏⴽ: ⴽⵓ ⵢⴰⵏ ⴷⴰⵔ ⵉⵍⵍⴰ ⵓⵙⵖⵏ ⵉⵣⵎⵔ ⴰⴷ ⵉⴽⴽⵙ ⴰⵎⵙⴰⴳⴰⵔ ⵙ ⵓⵎⴰⵜⴰ, ⵉⵎⵉⵍ ⴰⴷ ⵉⴷⴷⵓ ⴽⵓⵍⵍⵓ ⵎⴰ ⵉⵍⵍⴰⵏ ⵉ ⴱⴷⴷⴰ. ⵎⴽ ⵓⵔ ⵜ ⵉⴽⴽⵉⵙ ⵢⴰⵏ, ⴰⴷ ⵉⵇⵇⵉⵎ 12 ⵏ ⵡⴰⵢⵢⵓⵔⵏ ⴹⴰⵕⵜ ⵜⵎⵙⴽⵔⵜ ⵜⴰⵎⴳⴳⴰⵔⵓⵜ ⴰⴼⴰⴷ ⴰⴷ ⵜⵣⵎⵔⴷ ⴰⴷ ⵜⴰⵖⵓⵍⴷ, ⵉⵎⵉⵍ ⴰⴷ ⵉⵜⵜⵓⴽⴽⵙ ⵙ ⵓⵡⵓⵔⵎⴰⵏ.'],
 h=['ⵎⴰ ⵉⵜⵜⵃⴹⴰ Whenly','ⵎⴰ ⵓⵔ ⵉⵙⴽⴰⵔ Whenly','ⵎⴰ ⵉⵣⵎⵔⵏ ⴰⴷ ⵉⵥⵕ ⴰⵎⵙⴰⴳⴰⵔ','ⵎⵏⵛⴽ ⵏ ⵜⵉⵣⵉ, ⴷ ⵎⴰ ⵉⵜⵜⵖⵜⴰⵙⵏ','ⵎⴰⵏⵉ, ⴷ ⵉⵙⵇⵙⵉⵜⵏ'],
 p=['ⵖⴰⵙ ⵎⴰ ⵜⵓⵔⵉⴷ ⵙ ⵓⴼⵓⵙ ⵏⵏⴽ: ⴰⵣⵡⵍ ⵏ ⵓⵎⵙⴰⴳⴰⵔ, ⵉⵙⵎⴰⵡⵏ ⵏ ⵉⵎⴷⵔⴰⵡⵏ, ⵓⵙⵙⴰⵏ ⵉⵜⵜⵓⵙⵜⴰⵢⵏ ⴷ ⵜⴰⵙⵔⴰⴳⵜ ⵎⴽ ⵜⵔⵉⴷ. ⵡⴰⵍⵓ ⵢⴰⴹⵏ. ⴱⵍⴰ ⵉⵎⴰⵢⵍ, ⴱⵍⴰ ⵓⵟⵟⵓⵏ ⵏ ⵓⵜⵉⵍⵉⴼⵓⵏ, ⴱⵍⴰ ⴰⵎⵉⴹⴰⵏ, ⴱⵍⴰ ⵜⴰⴳⵓⵔⵉ ⵏ ⵓⵣⵔⴰⵢ.',
    'ⴱⵍⴰ ⴰⴹⴼⴰⵕ, ⴱⵍⴰ ⵉⵙⴷⴰⵡⵏ, ⴱⵍⴰ ⵉⴽⵓⴽⵉⵣ ⵏ ⵡⵉⵢⵢⴰⴹ, ⴱⵍⴰ ⵜⴰⵙⵍⴹⵜ. ⴰⵎⵙⵙⴰⵔⴰ ⵏⵏⴽ ⴰⵔ ⵉⵙⵙⵉⴽⵜⵉ ⵖⴰⵙ ⵜⵓⵜⵍⴰⵢⵜ ⵏⵏⴽ, ⵉⵙⵎ ⵏⵏⴽ ⴷ ⵉⵎⵙⴰⴳⴰⵔⵏ ⵏⵏⴰ ⵜⵕⵥⵎⴷ, ⴰⴼⴰⴷ ⵓⵔ ⵜⴰⵔⴰⴷ ⵡⴰⵍⵓ ⵜⵉⴽⴽⵍⵜ ⵢⴰⴹⵏ. ⴰⵢⴰ ⴰⵔ ⵉⵜⵜⵉⵍⵉ ⴳ ⵓⵎⴰⵙⵙ ⵏⵏⴽ.',
    'ⴽⵓ ⵢⴰⵏ ⴷⴰⵔ ⵉⵍⵍⴰ ⵓⵙⵖⵏ. ⴰⵙⵖⵏ ⵉⴳⴰ ⵢⴰⵜ ⵜⵏⴳⴰⵍⵜ ⵜⴰⵖⵣⵣⴰⴼⵜ ⵓⵔ ⵉⵣⵎⵔⵏ ⵢⴰⵏ ⴰⴷ ⵜⵜ ⵢⴰⴼ, ⴷ ⵜⴰⵙⵏⵉⵡⵉⵏ ⵏ ⵉⵎⵙⴰⴳⴰⵔⵏ ⵓⵔ ⵜⵜⵉⵍⵉⵏⵜ ⴳ ⵉⵎⵙⵙⵓⴼⵖⵏ ⵏ ⵓⵔⵣⵣⵓ; ⴱⴹⵓ ⴰⵙⵖⵏ ⵖⴰⵙ ⴷ ⵜⵔⴰⴱⴱⵓⵜ ⵏⵏⴽ. ⴽⵓ ⵢⴰⵏ ⴷⴰⵔ ⵉⵍⵍⴰ ⵓⵙⵖⵏ ⵉⵣⵎⵔ ⵓⵍⴰ ⴰⴷ ⵉⵙⵏⴼⵍ ⵏⵖ ⴰⴷ ⵉⴽⴽⵙ ⵉⵙⵎⴰⵡⵏ ⴷ ⵡⵓⵙⵙⴰⵏ; ⵎⴽ ⵉⴽⴽⵙ ⵢⴰⵏ ⵉⵙⵎ, ⴰⵔ ⵜⵇⵇⵉⵎ ⵢⴰⵜ ⵜⵎⴰⵜⴰⵔⵜ ⵜⴰⵎⵥⵥⴰⵏⵜ 30 ⵏ ⵡⴰⵙⵙ ⴰⴼⴰⴷ ⴰⴷ ⵜⵙⵙⵏ ⵜⵔⴰⴱⴱⵓⵜ ⵎⴰⵙ ⵓⵔ ⵉⴳⵉ ⵜⴰⵣⴳⵍⵜ ⵏ ⵜⵙⵏⵙⵉ.',
    'ⴽⵢⵢⵉ. ⵜⴰⵎⴰ ⵏ ⵓⵣⵡⵍ ⵉⵍⵍⴰ «ⴽⴽⵙ ⴰⵎⵙⴰⴳⴰⵔ ⴰⴷ ⵙ ⵓⵎⴰⵜⴰ». ⵙⵉⵜ ⵅⴰⴼⵙ (ⴷ ⵙⴷⴷⵉⴷ), ⵉⵎⵉⵍ ⴰⴷ ⵉⴷⴷⵓ ⵓⵣⵡⵍ, ⴽⵓ ⵉⵙⵎⴰⵡⵏ ⴷ ⴽⵓ ⵓⵙⵙⴰⵏ ⵉⵜⵜⵓⵙⵜⴰⵢⵏ ⵖⵉⵍⴰ ⴷ ⵉ ⴱⴷⴷⴰ, ⵉ ⴽⵓ ⵢⴰⵏ. ⵎⴽ ⵓⵔ ⵜ ⵉⴽⴽⵉⵙ ⵢⴰⵏ, ⴰⴷ ⵉⵇⵇⵉⵎ ⵓⵎⵙⴰⴳⴰⵔ 12 ⵏ ⵡⴰⵢⵢⵓⵔⵏ ⴹⴰⵕⵜ ⵜⵎⵙⴽⵔⵜ ⵜⴰⵎⴳⴳⴰⵔⵓⵜ ⴰⴼⴰⴷ ⴰⴷ ⵜⵣⵎⵔⴷ ⴰⴷ ⵜⴰⵖⵓⵍⴷ. ⵓⵔ ⵉⴳⵉ ⴰⵢⴰ ⵉ ⵓⵙⵎⵓⵏ ⵏ ⵉⵙⴼⴽⴰ; ⴹⴰⵕⵜ ⵓⵢⴰ ⴰⴷ ⵉⵜⵜⵓⴽⴽⵙ ⵙ ⵓⵡⵓⵔⵎⴰⵏ. ⵉⵙⵎ ⵉⵜⵜⵓⴽⴽⵙⵏ ⴰⵔ ⵉⵜⵜⴷⴷⵓ ⵉ ⴱⴷⴷⴰ ⴹⴰⵕⵜ 30 ⵏ ⵡⴰⵙⵙ.',
    'ⵉⵙⴼⴽⴰ ⵍⵍⴰⵏ ⴳ ⵉⵙⵔⴱⴷⵏ ⵏ Cloudflare. Whenly ⵉⴳⴰ ⴰⵖⴱⴰⵍⵓ ⵢⵓⵔⵥⵎⵏ; ⵜⴰⵏⴳⴰⵍⵜ ⴷ ⵉⵙⵇⵙⵉⵜⵏ ⵍⵍⴰⵏ ⴳ GITHUB.'])

P['ku'] = dict(
 faq_title='Pirsên pir tên pirsîn', priv_title='Nepenîtî', open='Whenly veke', faq='Pirs', privacy='Nepenîtî',
 q=['Whenly belaş e?','Hesab pêwîst e?','Li ser telefona min dixebite?','Whenly kîjan zimanan piştgirî dike?','Ji Doodle çi cuda ye?','Ez dikarim ji bo kesekî din dagirim?','Kî dikare anketa min bibîne?','Bi daneyên min çi dibe?'],
 a=['Erê. Whenly bi tevahî belaş e û wê belaş bimîne. Ne dîwarê pereyan, ne reklam.',
    'Na. Kes hewceyî hesabekê nîne, ne jî yê ku anketê çêdike. Tu navê xwe dinivîsî û rojên xwe nîşan dikî.',
    'Erê. Whenly di her gerokê de dixebite û wek sepanekê li ekrana destpêkê tê zêdekirin, bê dikana sepanan.',
    'Bîst û sê, di nav wan de Kurdî, Îngilîzî, Fransî, Erebî, Hindî, Çînî, Rûsî, Tamazîxt û Şona. Ziman li gorî geroka te ye û bi bişkoka cîhanê tê guhertin.',
    'Whenly ji kesî tomarkirin naxwaze, reklaman nîşan nade û belaş e. Tu rojan li ser salnameyê nîşan dikî, û ronahiyeke trafîkê nîşan dide kengî her kes dikare.',
    'Erê. "Beşdarekî zêde bike" hilbijêre, navekî binivîse û rojan ji bo wî kesî nîşan bike.',
    'Her kesê ku lînk pê re ye. Lînk kodeke dirêj û tesadufî ye ku nayê texmînkirin, û rûpelên anketan ji aliyê motorên lêgerînê ve nayên tomarkirin. Lînkê tenê bi koma xwe re parve bike.',
    'Tenê sernav, nav û rojên nîşankirî tên tomarkirin, tiştekî din na. Ne e-name, ne hejmara telefonê, ne şopandin. Kontrol di destê te de ye: her kesê bi lînkê dikare anketê bi tevahî jê bibe, û wê demê her tişt ji bo her dem winda dibe. Heke kes jê nebe, piştî çalakiya dawî 12 mehan dimîne da ku tu vegerî, paşê bixweber tê jêbirin.'],
 h=['Whenly çi tomar dike','Whenly çi nake','Kî dikare anketekê bibîne','Çiqas dirêj, û kî biryar dide','Li ku, û pirs'],
 p=['Tenê tiştên ku tu bi xwe dinivîsî: sernavê anketê, navên beşdaran, rojên nîşankirî û demeke bijartî. Tiştekî din na. Ne e-name, ne hejmara telefonê, ne hesab, ne şîfre.',
    'Ne şopandin, ne reklam, ne cookieyên aliyê sêyem, ne analîtîk. Geroka te tenê zimanê te, navê te û anketên ku te vekirine bi awayekî herêmî bi bîr tîne, da ku tu tiştekî dîsa nenivîsî. Ew li ser amûra te dimîne.',
    'Her kesê ku lînk pê re ye. Lînk kodeke dirêj û tesadufî ye ku nayê texmînkirin, û rûpelên anketan ji aliyê motorên lêgerînê ve nayên tomarkirin; lînkê tenê bi koma xwe re parve bike. Her kesê bi lînkê dikare navan û rojan biguherîne an jê bibe; dema kesek navekî jê dibe, nîşeyeke kurt 30 rojan xuya dimîne da ku kom bizane ku ew ne xeletiya sepanê bû.',
    'Tu. Li kêleka sernavê "Vê anketê bi tevahî jê bibe" heye. Bitikîne (û piştrast bike), sernav, hemû nav û hemû rojên nîşankirî tavilê û ji bo her dem winda dibin, ji bo her kesî. Heke kes jê nebe, anket piştî çalakiya dawî 12 mehan dimîne da ku tu vegerî. Ev ne ji bo berhevkirina daneyan e; paşê bixweber tê jêbirin. Navekî jêbirî piştî 30 rojan ji bo her dem winda dibe.',
    'Dane li ser serverên Cloudflare tên tomarkirin. Whenly çavkaniya vekirî ye; kod û pirs li ser GITHUB in.'])

P['sn'] = dict(
 faq_title='Mibvunzo inowanzobvunzwa', priv_title='Zvakavanzika', open='Vhura Whenly', faq='Mibvunzo', privacy='Zvakavanzika',
 q=['Whenly imahara here?','Ndinoda account here?','Inoshanda pafoni yangu here?','Whenly inoshandisa mitauro ipi?','Mutsauko neDoodle ndeupi?','Ndingazadzire mumwe munhu here?','Ndiani anogona kuona poll yangu?','Chii chinoitika kudata yangu?'],
 a=['Hongu. Whenly imahara zvachose uye icharamba iri mahara. Hapana kubhadhara, hapana zvishambadzo.',
    'Kwete. Hapana anoda account, kunyange anogadzira poll. Unonyora zita rako wosarudza mazuva ako.',
    'Hongu. Whenly inoshanda mubrowser chero ipi uye inogona kuiswa pahome screen seapp, pasina app store.',
    'Makumi maviri nemitatu, kusanganisira chiShona, Chirungu, French, Arabic, Hindi, Chinese, Russian, Tamazight neKurdish. Mutauro unotevera browser yako uye unogona kuchinjwa nebhatani renyika.',
    'Whenly haikumbiri munhu kunyoresa, hairatidzi zvishambadzo uye imahara. Unosarudza mazuva pacalendar, uye traffic light inoratidza kuti vese vanokwanisa rinhi.',
    'Hongu. Sarudza "Wedzera nhengo", nyora zita wosarudza mazuva emunhu iyeye.',
    'Chero ane link. Link icode refu risingafungidzirwi, uye mapeji epoll haaiswi musearch engines. Govera link nechikwata chako chete.',
    'Musoro, mazita nemazuva akasarudzwa chete ndizvo zvinochengetwa, hapana zvimwe. Hapana email, hapana nhamba yefoni, hapana kutevera. Kutonga ndekwako: chero ane link anogona kudzima poll zvachose, uye zvese zvinobva zvaenda zvachose. Kana pasina anodzima, inogara mwedzi gumi nemiviri mushure mechiitiko chekupedzisira kuti ugone kudzoka, yobva yadzimwa yega.'],
 h=['Zvinochengetwa neWhenly','Zvisingaitwe neWhenly','Ndiani anogona kuona poll','Kwenguva yakareba sei, uye ndiani anosarudza','Kupi, nemibvunzo'],
 p=['Zvaunonyora iwe chete: musoro wepoll, mazita evatori vechikamu, mazuva akasarudzwa uye nguva kana uchida. Hapana zvimwe. Hapana email, hapana nhamba yefoni, hapana account, hapana password.',
    'Hapana kutevera, hapana zvishambadzo, hapana cookies dzevamwe, hapana analytics. Browser yako inongoyeuka pamudziyo mutauro wako, zita rako nemapoll awakavhura, kuti usanyore zvakare. Izvo zvinogara pamudziyo wako.',
    'Chero ane link. Link icode refu risingafungidzirwi, uye mapeji epoll haaiswi musearch engines; govera link nechikwata chako chete. Chero ane link anogonawo kuchinja kana kubvisa mazita nemazuva; kana mumwe akabvisa zita, tsamba pfupi inoramba ichionekwa mazuva makumi matatu kuti chikwata chizive kuti hachisi chikanganiso cheapp.',
    'Iwe. Padivi pemusoro pane "Dzima poll iyi zvachose". Dzvanya (uye simbisa), musoro, mazita ese nemazuva ese akasarudzwa anobva aenda pakarepo uye zvachose, kune vese. Kana pasina anodzima, poll inogara mwedzi gumi nemiviri mushure mechiitiko chekupedzisira kuti ugone kudzoka. Hazvisi zvekuunganidza data; mushure meizvozvo inodzimwa yega. Zita rakabviswa rinonyangarika zvachose mushure memazuva makumi matatu.',
    'Data inochengetwa pamaserver eCloudflare. Whenly iopen source; code nemibvunzo zviri paGITHUB.'])
